### ISSUE TITLE
rstudio: Uses an old version of RStudio

### ISSUE THREAD

**Issue by mineo** [ppc64le/build-scripts#1]
The most recent version appears to be 1.1.442: https://www.rstudio.com/products/rstudio/download/

**Comment by seth-priya** [comment]
Thanks for reaching out! In general, we build and publish images against specific requests and do not actively maintain the currency of these.

**Comment by gerrith3** [comment]
While Priya is correct, we do update based on business need any images as
bandwidth is available.  We have a very small team and a very large
pipeline but we do take requests.  I'm viewing this as a new request.


gerrit

--
"Only those who will risk going too far can possibly find out how far one
can go." ~ T. S. Eliot

Gerrit Huizenga, STSM
Power Open Source Ecosystem Lead
gerrit@us.ibm.com

**Comment by asowani** [comment]
Docker file for RStudio version 1.1.447 is available at https://github.com/ppc64le/build-scripts/tree/master/rstudio/Dockerfiles/1.1.447_ubuntu_16.04 which addresses this issue.
