### ISSUE TITLE
Update istio build script

### ISSUE THREAD

**Issue by MatthieuSarter** [ppc64le/build-scripts#1213]
Update istio build-script to allow building istio 1.12.0

**Comment by gerrith3** [comment]
Amit can this be assigned to Rashmi for review?

**Comment by seth-priya** [comment]
@rashmi-ibm ^^

**Comment by kandarpamalipeddi** [comment]
@seth-priya ,
Can we close this as we already merged build script Istio version 1.12.0 (https://github.com/ppc64le/build-scripts/blob/master/i/istio/build.sh)

**Comment by seth-priya** [comment]
closing, please feel free to open another issue if the above does not address the problem
