### ISSUE TITLE
Typo in env name for RStudio

### ISSUE THREAD

**Issue by aryoda** [ppc64le/build-scripts#127]
`ENV 	RStduio_VERSION 1.2.1335`

should be

`ENV 	RStudio_VERSION 1.2.1335`

in

[(https://github.com/ppc64le/build-scripts/blob/master/rstudio/Dockerfiles/v1.2.1335/Dockerfile)]

(line 5)

**Comment by ghatwala** [comment]
thanks @aryoda  - done - https://github.com/ppc64le/build-scripts/blob/master/rstudio/Dockerfiles/v1.2.1335/Dockerfile#L6

**Comment by aryoda** [comment]
Sorry for having reported the impact of the typo incompletely, but the variable name with the type was used allover the Dockerfile so all wrong names must be fixed, eg. in line 16 and 17:

`tar zxvf v${RStduio_VERSION}.tar.gz && \
`

https://github.com/ppc64le/build-scripts/blob/master/rstudio/Dockerfiles/v1.2.1335/Dockerfile#L17

**Comment by ghatwala** [comment]
Apologies , missed that as was in hurry to update , changed in all relevant place.
