### ISSUE TITLE
rstudio: Docker run command on docker hub doesn't work

### ISSUE THREAD

**Issue by mineo** [ppc64le/build-scripts#2]
https://hub.docker.com/r/ibmcom/rstudio-ppc64le/ says:

```
Docker run command:
docker run -it rstudio
```

That doesn't work:

```
# docker run -it rstudio
Unable to find image 'rstudio:latest' locally
docker: Error response from daemon: repository rstudio not found: does not exist or no pull access.
See 'docker run --help'.
```

**Comment by seth-priya** [comment]
Please specify one of the supported tags (version) and ppc64le suffix
**Example:** docker run -it ibmcom/rstudio-ppc64le:0.99

Updated example at https://hub.docker.com/r/ibmcom/rstudio-ppc64le/

**Comment by seth-priya** [comment]
Closing, as I believe that this should now be resolved.
