### ISSUE TITLE
rstudio 1.3.1073

### ISSUE THREAD

**Issue by sebacea** [ppc64le/build-scripts#258]
Hi, Is there a possibility to update Dockerfiles in https://github.com/ppc64le/build-scripts/tree/master/rstudio/Dockerfiles to support the newest version of RStudio and possibly R version 4.0.2

Thanks

**Comment by sebacea** [comment]
I've tried with `ENV     RStduio_VERSION 1.3.1073` in https://github.com/ppc64le/build-scripts/blob/master/rstudio/Dockerfiles/v1.2.1335/Dockerfile_R_3.6.1 but I got the following 

```Error: Unsupported Debian release                                                                              The command '/bin/sh -c wget https://github.com/rstudio/rstudio/archive/v${RStduio_VERSION}.tar.gz &&         tar zxvf v${RStduio_VERSION}.tar.gz &&         mkdir -p /rstudio-${RStduio_VERSION}/build &&         cd /rstudio-${RStduio_VERSION}/dependencies/linux &&         ./install-dependencies-debian --exclude-qt-sdk &&         cd /rstudio-${RStduio_VERSION}/build &&         cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release &&         make install &&         useradd -r rstudio-server  &&         cp /usr/local/lib/rstudio-server/extras/init.d/debian/rstudio-server /etc/init.d/ &&         update-rc.d rstudio-server defaults &&         ln -f -s /usr/local/lib/rstudio-server/bin/rstudio-server /usr/sbin/rstudio-server &&         mkdir -p /var/run/rstudio-server &&         mkdir -p /var/lock/rstudio-server &&         mkdir -p /var/log/rstudio-server &&         mkdir -p /var/lib/rstudio-server &&         set -e && useradd -m -d /home/rstudio -G sudo rstudio &&         echo rstudio:rstudio | chpasswd &&         rstudio-server online && cd / &&         echo -e '#!/bin/bash\ncd /usr/sbin\nrstudio-server start' >> startup.sh &&         chmod +x startup.sh' returned a non-zero code: 1 ```

**Comment by gerrith3** [comment]
@sebacea did you copy/paste or re-type your line with ENV above - RStudio has a typo.  Not saying that is the problem.  Apologies for the delay in responding, our team has been very loaded lately but we'll try to get you a more complete answer in the next few days.

**Comment by sebacea** [comment]
@gerrith3 the typo is also present in the code. But, as you noticed, it is not the problem because the typo is consistent in the Dockerfile

**Comment by gerrith3** [comment]
Haha okay - we have to fix that, too, then!  ;)  Thanks for the bug report and the enhancement request, all in one.

**Comment by seth-priya** [comment]
@sebacea @gerrith3 sorry for the delay on this. I will coorect the typo, and the above error that you are seeing is likely due to the fact that the base image https://hub.docker.com/r/ppc64le/openjdk/ used in this Dockerfile is now no longer supported officially for Power , so we will likely need to use an equivalent adoptopenjdk image as the base

**Comment by seth-priya** [comment]
FYI, I am trying to build this with adoptopenjdk:8-jdk-openj9-bionic as the base, however the build for R-4.0.2 is failing with what looks like a change in the dependency list, I am looking into this but it may take a bit to get through the build completely..

**Comment by ezeeyahoo** [comment]
@sebacea 
I am trying with 
ENV     R_VERSION 4.0.2
ENV     RStudio_VERSION 1.3.1073

Progress: R-4.0.2 is installing
Question is- PCRE2 is recommended for regex during build but pcre1 flag can be used. I have used --with-pcre1 for now.

**Comment by ezeeyahoo** [comment]
New crashpad module(crash reporting) is disabled for now and script is failing in final steps. Expecting to get it sorted soon.
```
Installation path: /usr/local/bin/sentry-cli
Warning: this script is currently running as root. This is dangerous.
         Instead run it as normal user. We will sudo as needed.
error: your platform and architecture (Linux-ppc64le) is unsupported.
**CMake Error: The source directory "/rstudio-1.3.1073/dependencies" does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by ezeeyahoo** [comment]
Wrt new version of Dockerfile, I have cleaned and rebuilt the image. Could you please rm older images and exited/running containers using same name image, prune and do a clean rebuild?

![image](https://user-images.githubusercontent.com/3622762/93907662-41e9b100-fd1b-11ea-951e-92d353b9c384.png)

**Comment by ezeeyahoo** [comment]
it is not working for me after `docker build -t`, I got

```
[ 56%] Building CXX object src/cpp/server/CMakeFiles/rserver.dir/ServerAddins.cpp.o
[ 56%] Linking CXX executable rserver
[ 56%] Built target rserver
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c echo "exit 0" > /rstudio-${RStudio_VERSION}/dependencies/common/install-crashpad &&         cd /rstudio-${RStudio_VERSION}/dependencies/linux &&         sed -i s/amd64/ppc64el/g ./install-dependencies-bionic &&         ./install-dependencies-bionic &&         cd /rstudio-${RStudio_VERSION}/build &&         cmake -j4 .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release &&         make -j4 install &&         useradd -r rstudio-server  &&         cp /usr/local/lib/rstudio-server/extras/init.d/debian/rstudio-server /etc/init.d/ &&         update-rc.d rstudio-server defaults &&         ln -f -s /usr/local/lib/rstudio-server/bin/rstudio-server /usr/sbin/rstudio-server &&         mkdir -p /var/run/rstudio-server &&         mkdir -p /var/lock/rstudio-server &&         mkdir -p /var/log/rstudio-server &&         mkdir -p /var/lib/rstudio-server &&         set -e && useradd -m -d /home/rstudio -G sudo rstudio &&         echo rstudio:rstudio | chpasswd &&         rstudio-server online && cd / &&         echo -e '#!/bin/bash\ncd /usr/sbin\nrstudio-server start' >> startup.sh &&         chmod +x startup.sh' returned a non-zero code: 2
```

_Originally posted by @sebacea in https://github.com/ppc64le/build-scripts/pull/269#issuecomment-696712136_
========================================================================================
Wrt new version of Dockerfile, I have cleaned and rebuilt the image once again as shown in the s/s. Could you please use a new name as it is not clear from the quoted command above? Lets give a new name ` docker build -t <new_name> .` and do a clean rebuild?

![image](https://user-images.githubusercontent.com/3622762/93910600-f33e1600-fd1e-11ea-8157-9a8354f9723a.png)

![image](https://user-images.githubusercontent.com/3622762/93907662-41e9b100-fd1b-11ea-951e-92d353b9c384.png)

**Comment by ezeeyahoo** [comment]
It works! Many, many thanks!

_Originally posted by @sebacea in https://github.com/ppc64le/build-scripts/pull/269#issuecomment-696898997_

Hence closing the issue.
Thanks
