### ISSUE TITLE
Hope there will be mxnet build scripts for ppc64le + redhat 7.5

### ISSUE THREAD

**Issue by sphinx-jiang** [ppc64le/build-scripts#27]

**Comment by seth-priya** [comment]
@sphinx-jiang  - are you building mxnet on CPU or GPU based setup? Have you tried using the RHEL 7.4 script .. in general I would expect it to run without issues on RHEL 7.5 as well ... could you please try?

**Comment by sphinx-jiang** [comment]
I need GPU based setup on RHEL, so I tried CentOS gpu shell.

It failed here:
If needed I could paste whole log later.
a - build/src/kvstore/gradient_compression_gpu.o
a - build/src/kvstore/kvstore_utils_gpu.o
/bin/ld: warning: libfribidi.so.0, needed by //usr/lib64/libpango-1.0.so.0, not found (try using -rpath or -rpath-link)
//usr/lib64/libpango-1.0.so.0: undefined reference to `fribidi_get_bidi_type'
//usr/lib64/libpango-1.0.so.0: undefined reference to `fribidi_get_bracket'
//usr/lib64/libpangoft2-1.0.so.0: undefined reference to `g_log_structured_standard'
//usr/lib64/libpango-1.0.so.0: undefined reference to [`fribidi_get_par_embedding_levels_ex']([url](url))
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1
+ rm -rf build

**Comment by sphinx-jiang** [comment]
Another question is the install shell just use system python env. However we need work with different python version in anaconda.

**Comment by gerrith3** [comment]
@seth-priya can you look at the errors when you get a chance?  Looks like some dependencies are missing.  If you can identify, maybe @sphinx-jiang can update and re-test?

**Comment by sandipmgiri** [comment]
@sphinx-jiang 
https://github.com/ppc64le/build-scripts/blob/master/mxnet/Dockerfiles/latest_centos_7_gpu/Dockerfile   These steps are working fine for me on centos+GPU with latest mxnet source code. Can you please try ?

**Comment by sandipmgiri** [comment]
Centos version used in nvidia/cuda-ppc64le:9.0-cudnn7-devel-centos7 image is : 

```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (AltArch)
```

**Comment by sphinx-jiang** [comment]
It has been solved already, user need select commands they need from the script, not run the script directly. Thanks all of you.

Hope all packages of ppc64le supported in anaconda officially. Currently for data scientists, using ppc64le on redhat, is totally nightmare:)
