### ISSUE TITLE
rstudio: Docker pull command on docker hub doesn't work

### ISSUE THREAD

**Issue by mineo** [ppc64le/build-scripts#3]
https://hub.docker.com/r/ibmcom/rstudio-ppc64le/ says:

```
Docker Pull Command
docker pull ibmcom/rstudio-ppc64le
```

That doesn't work:

```
# docker pull ibmcom/rstudio-ppc64le
Using default tag: latest
Error response from daemon: manifest for ibmcom/rstudio-ppc64le:latest not found
```

**Comment by seth-priya** [comment]
Please specify one of the supported tags (version) 
**Example:** docker pull ibmcom/rstudio-ppc64le:0.99

Added example at https://hub.docker.com/r/ibmcom/rstudio-ppc64le/

**Comment by seth-priya** [comment]
Closing, as I believe that this should now be resolved.
