### ISSUE TITLE
rstudio: Just starts bash by default

### ISSUE THREAD

**Issue by mineo** [ppc64le/build-scripts#4]
https://github.com/ppc64le/build-scripts/blob/03d26f8876c2d324958e07bf3e44c89e2b3ec12f/rstudio/Dockerfiles/0.99.903_ubuntu_14.04/Dockerfile#L56 just starts `/bin/bash` when the container is started.

**Comment by asowani** [comment]
@mineo I am working on modifying current docker file to cater this issue as well as other issues reported by you.

**Comment by asowani** [comment]
Docker file for RStudio version 1.1.447 is now available at https://github.com/ppc64le/build-scripts/tree/master/rstudio/Dockerfiles/1.1.447_ubuntu_16.04 which addresses this issue.
