### ISSUE TITLE
rstudio: Can't connect to RStudio after manually starting rstudio-server

### ISSUE THREAD

**Issue by mineo** [ppc64le/build-scripts#5]
After running `docker run -it ibmcom/rstudio-ppc64le:0.99`, and `/usr/sbin/rstudio-server start` in the container, I can't connect to the web UI. I need to additionally specify `-p 8787:8787` in the run command.

**Comment by asowani** [comment]
Docker file for RStudio version 1.1.447 is available at https://github.com/ppc64le/build-scripts/tree/master/rstudio/Dockerfiles/1.1.447_ubuntu_16.04 which addresses this issue.
