### ISSUE TITLE
No cuDNN library available for Tensorflow on ppc64le + Ubuntu

### ISSUE THREAD

**Issue by trstovall** [ppc64le/build-scripts#7]
The cuDNN prerequisite is amd64 + Ubuntu or ppc64le + RHEL (given here: 
 https://docs.nvidia.com/deeplearning/sdk/cudnn-install/).

Is there a version of the library that allows CUDA acceleration of Tensorflow on ppc64le + Ubuntu?

**Comment by sandipmgiri** [comment]
Yes , you can install CUDA and cuDNN on Ubuntu_ppc64le, please follow the instructions mentioned here - https://www.nvidia.com/en-us/data-center/gpu-accelerated-applications/tensorflow/

**Comment by seth-priya** [comment]
Hi @trstovall -just to add to what Sandip has mentioned above, cuDNN for Ubuntu + ppc64le can be downloaded from here
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=ppc64le&target_distro=Ubuntu&target_version=1604

Hope this answers your query, please let us know in case you have any further questions.
