### ISSUE TITLE
tcl/tk capability

### ISSUE THREAD

**Issue by sebacea** [ppc64le/build-scripts#703]
Hi, it would be nice to add tcl/tk capability to the last Dockerfile you have:

https://github.com/ppc64le/build-scripts/blob/master/r/rstudio/Dockerfiles/v1.3.1073/Dockerfile

Thanks!

**Comment by gerrith3** [comment]
@seth-priya can you assign this to someone that worked on rstudio to see what this would imply?  @sebacea do you happen to have patches available for this?

**Comment by sebacea** [comment]
This is my proposal: #706

**Comment by gerrith3** [comment]
@sebacea apologies that this got forgotten.  I see no issue with it as it stands.  My only concern pre-dates your patch, which is:  did we pre-clean the container from unnecessary build cruft, e.g. the container might be able to be smaller if cleaned.  But I'm going to ignore that for now and apply this patch.
