### ISSUE TITLE
Configuring Tensorflow with Bazel is failing

### ISSUE THREAD

**Issue by trstovall** [ppc64le/build-scripts#8]
Bazel is attempting to download many files which are hosted by the project mirror (mirror.bazel.build) which are blocked by Walmart firewalls.  Can I get a contact to reach out on possibly providing a precompiled .whl, or the PowerAI framework?  

Thomas Stovall
thomas [dot] stovall [at] walmart [dot] com

**Comment by hartb** [comment]
If you're able to pull from docker hub, there's an Ubuntu 16.04-based PowerAI 1.5.2 image available:

https://hub.docker.com/r/ibmcom/powerai/

That image has Bazel 1.10 (and the rest of PowerAI, including TF 1.8.0) pre-installed. You could use the included TF binary, or just use the Bazel to build your own TF.

Even with a pre-buildt Bazel, the TF build itself will want to pull code from many different repos, so may be a challenge behind a firewall. You may also want to check out:

ftp://ftp.unicamp.br/pub/ppc64el/ai_frameworks/tensorflow/

There you'll find a TensorFlow 1.8 whl built for ppc64le with GPU support.

**Comment by asowani** [comment]
@trstovall Did you try pulling the docker hub image as mentioned by @hartb ? Did that solve your problem?

**Comment by asowani** [comment]
Closed, reopen if issue persists.
